#!/bin/bash

source config

for file in folder/*; do 
	if (($(stat -c%s $file) < $size))
	then
		name=$(basename $file)
		f3=${name:0:3}
		mv "$file" "${file%.*}.$f3"  	
	else
		echo "big"
	fi
		
done

