#!/bin/bash

source config

for file in folder/*; do 
	if (($(stat -c%s $file) < $size))
	then
		name=$(basename $file)
		nosuff=${name%.*}
		len=$((${#name}-${#nosuff}-1))
		f3=${name:0:len}
		new=${file%.*}.$f3
		mv "$file" "$new"  	
		echo "file name changed from $name to $new"
	else
		echo "file $file is too big to rename"
	fi
		
done


